### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by thiagopaiva99** [viniciuslagedo/ng-accessibility-bar#35]
Seria interessante colocar uma demo, não? 

Achei o projeto importante e interessante e gostaria de contribuir com ele!

**Comment by viniciuslagedo** [comment]
Ótima sugestão, vou tentar adicionar isso essa semana ainda.
Criar uma pastinha example ou demo.

**Comment by thiagopaiva99** [comment]
Ótimo! isso vai ajudar o pessoal a ver se é realmente esse componente que eles precisam! Se precisar de uma mão só chamar!

**Comment by viniciuslagedo** [comment]
Pasta example criada !
